cache:
  directories:
    - $HOME/.pub-cache
    - $HOME/Library/Caches/Homebrew

jobs:
  include:
    - os: linux
      name: android
      if: branch = master
      dist: bionic
      language: java
      jdk:
        - oraclejdk11
      env:
        - ANDROID_SDK_TOOLS=commandlinetools-linux-6200805_latest.zip
      before_install:
        - sudo apt update
        #- export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
        - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
        - export PATH=$PATH:$HOME/sdk/tools/bin
        - export ANDROID_HOME=$HOME/sdk
        - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
        - yes | sdkmanager --licenses --sdk_root="${ANDROID_HOME}"
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
        - flutter doctor
      script:
        - flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        - flutter build appbundle --target-platform android-arm,android-arm64,android-x64
      before_deploy:
        - export TRAVIS_TAG="$TRAVIS_BUILD_NUMBER"
        - git tag TRAVIS_TAG
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH"
        file:
          - build/app/outputs/bundle/release/app-release.aab
          - build/app/outputs/apk/release/app-armeabi-v7a-release.apk
          - build/app/outputs/apk/release/app-arm64-v8a-release.apk
          - build/app/outputs/apk/release/app-x86_64-release.apk
        skip_cleanup: true
        on:
          branch: master
    - os: osx
      name: apple
      if: branch = master
      osx_image: xcode11.5
      before_install:
        - brew update
        - brew install --HEAD usbmuxd
        - brew unlink usbmuxd
        - brew link usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy;
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
      before_deploy:
        - pushd build/ios/iphoneos
        - mkdir Payload
        - cd Payload
        - ln -s ../Runner.app
        - cd ..
        - zip -r app.ipa Payload
        - popd
        - export TRAVIS_TAG="$TRAVIS_BUILD_NUMBER"
        - git tag TRAVIS_TAG
      script:
        - flutter/bin/flutter build ios --debug --no-codesign
      before_cache:
        - brew cleanup
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH"
        file:
          - build/ios/iphoneos/app.ipa
        skip_cleanup: true
        on:
          branch: master