# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload a new build to google play"
  lane :alpha do
    upload_to_play_store(track: "alpha", aab: "bundle-signed.aab", json_key:"play.json", skip_upload_apk: true)
    discord_notifier(
        webhook_url: ENV["DISCORD_WEBHOOK"],
        title: "New Alpha Deployment",
        description: "Build " + ENV["TRAVIS_BUILD_NUMBER"] + " was deployed to Google Play.",
      )
  end
end
