name: Flutter Build
on: [push]
jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: ios_build_artifact
          path: build/ios/iphoneos/Drinkr.app
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: android_build_artifact_apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: android_build_artifact_appbundle
          path: build/app/outputs/bundle/release/app-release.aab
  sign_android_appbundle:
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_appbundle
      - run: zip --delete app-release.aab "META-INF/*"
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APPBUNDLE
        id: sign_appbundle
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v2
        with:
          name: android_signed_appbundle
          path: ${{steps.sign_appbundle.outputs.signedReleaseFile}}
  sign_android_apk:
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_apk
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_appapk
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v2
        with:
          name: android_signed_apk
          path: ${{steps.sign_appapk.outputs.signedReleaseFile}}
  upload_to_google_play:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    needs: sign_android_appbundle
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: android_signed_appbundle
      - run: mkdir whatsnew/
      - run: echo "Multiple Improvements." > whatsnew/whatsnew-en-US
      - run: echo "Verschiedene Verbesserungen." > whatsnew/whatsnew-de-DE
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: com.drinkr.android
          releaseFile: "app-release.aab"
          track: beta
          inAppUpdatePriority: 2
          whatsNewDirectory: whatsnew

  upload_to_github_releases:
    runs-on: ubuntu-latest
    needs: [sign_android_appbundle, sign_android_apk, build_ios]
    steps:
      - name: Download results from build
          uses: actions/download-artifact@v2
          with:
            name: android_build_artifact_appbundle