name: Flutter Build
on: [ push ]
jobs:
  build_ios:
    runs-on: macos-11
    env:
      APP_ID: ${{ secrets.APP_ID_IOS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: sed -i .bak "s|ca-app-pub-3940256099942544~3347511713|$APP_ID|g" ios/Runner/Info.plist
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: mkdir Payload
      - run: mv build/ios/iphoneos/Drinkr.app Payload/Drinkr.app
      - run: zip -r drinkr-app-release.zip ./Payload
      - run: mv drinkr-app-release.zip drinkr-app-release.ipa
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: ios_build_artifact
          path: drinkr-app-release.ipa
  build_android_no_ads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-no-ads.apk
      - run: mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/app-release-no-ads.aab
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: android_build_artifact_noad_apk
          path: build/app/outputs/flutter-apk/app-release-no-ads.apk
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: android_build_artifact_noad_appbundle
          path: build/app/outputs/bundle/release/app-release-no-ads.aab
  build_android:
    runs-on: ubuntu-latest
    env:
      APP_ID: ${{ secrets.APP_ID_ANDROID }}
      BANNER_ID: ${{ secrets.BANNER_ID_ANDROID }}
      REWARDED_ID: ${{ secrets.REWARDED_ID_ANDROID }}
      FULLSCREEN_ID: ${{ secrets.FULLSCREEN_ID_ANDROID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: sed -i "s|ca-app-pub-3940256099942544~3347511713|$APP_ID|g" android/app/src/main/AndroidManifest.xml
      - run: sed -i "s|ca-app-pub-3940256099942544~3347511713|$APP_ID|g" android/app/src/main/res/values/strings.xml
      - run: flutter pub get
      - run: flutter build apk --release --dart-define "ADS_ENABLED=true" --dart-define "BANNER_AD_ID=$BANNER_ID" --dart-define="REWARDED_AD_ID=$REWARDED_ID" --dart-define="INTERSTITIAL_AD_ID=$FULLSCREEN_ID"
      - run: flutter build appbundle --release --dart-define "ADS_ENABLED=true" --dart-define "BANNER_AD_ID=$BANNER_ID" --dart-define="REWARDED_AD_ID=$REWARDED_ID" --dart-define="INTERSTITIAL_AD_ID=$FULLSCREEN_ID"
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: android_build_artifact_apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: android_build_artifact_appbundle
          path: build/app/outputs/bundle/release/app-release.aab
  sign_android_appbundle:
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_appbundle
      - run: zip --delete app-release.aab "META-INF/*"
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APPBUNDLE
        id: sign_appbundle
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v2
        with:
          name: android_signed_appbundle
          path: ${{steps.sign_appbundle.outputs.signedReleaseFile}}
  sign_android_apk:
    runs-on: ubuntu-latest
    needs: build_android
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_apk
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_appapk
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v2
        with:
          name: android_signed_apk
          path: ${{steps.sign_appapk.outputs.signedReleaseFile}}
  upload_to_google_play:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    needs: sign_android_appbundle
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: android_signed_appbundle
      - run: mkdir whatsnew/
      - run: echo "Multiple Improvements." > whatsnew/whatsnew-en-US
      - run: echo "Verschiedene Verbesserungen." > whatsnew/whatsnew-de-DE
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: com.drinkr.android
          releaseFile: "app-release.aab"
          track: beta
          inAppUpdatePriority: 2
          whatsNewDirectory: whatsnew
  upload_to_apple_testflight:
    runs-on: macos-11
    if: github.ref == 'refs/heads/stable'
    needs: build_ios
    steps:
      - name: Download results from build
        uses: actions/download-artifact@v2
        with:
          name: ios_build_artifact
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'drinkr-app-release.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
  upload_to_github_releases:
    runs-on: ubuntu-latest
    needs: [ sign_android_appbundle, sign_android_apk, build_android_no_ads, build_ios ]
    steps:
      - name: Download results from build appbundle
        uses: actions/download-artifact@v2
        with:
          name: android_signed_appbundle
      - name: Download results from build apk
        uses: actions/download-artifact@v2
        with:
          name: android_signed_apk
      - name: Download results from build ios
        uses: actions/download-artifact@v2
        with:
          name: ios_build_artifact
      - name: Download results from build apk
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_apk
      - name: Download results from build noad apk
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_noad_apk
      - name: Download results from build noad appbundle
        uses: actions/download-artifact@v2
        with:
          name: android_build_artifact_noad_appbundle
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            *.aab
            *.apk
            *.ipa
